name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: flashlight.jar
          path: build/libs/flashlight.jar

      - name: Save test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: build/reports/tests/test

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: build/libs/flashlight.jar
